version: '2'
services:
    datainfo-app:
        image: datainfo
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://datainfo-postgresql:5432/datainfo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    datainfo-postgresql:
        extends:
            file: postgresql.yml
            service: datainfo-postgresql
