version: '2'
services:
    datainfo-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/datainfo/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=datainfo
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
